exclude: ^.+\.(txt|txtLogFile)$
repos:
  # Formatters
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: fix-encoding-pragma
        args: [--remove]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.3.1 # Use the sha or tag you want to point at
    hooks:
      - id: prettier

  # Notebook tools
  - repo: https://github.com/kynan/nbstripout
    rev: 0.4.0
    hooks:
      - id: nbstripout
        args: [--keep-count, --keep-output, --strip-empty-cells]

  - repo: https://github.com/nbQA-dev/nbQA
    rev: 0.13.0
    hooks:
      - id: nbqa-black
        additional_dependencies: [black==21.7b0]
        args: [--nbqa-mutate]
      - id: nbqa-pyupgrade
        additional_dependencies: [pyupgrade==2.23.1]
        args: [--nbqa-mutate, --py38-plus]
      - id: nbqa-flake8
      - id: nbqa-check-ast
      - id: nbqa-isort
        additional_dependencies: [isort==5.9.3]
        args: [--nbqa-mutate]

  - repo: https://github.com/MarcoGorelli/check-execution-order
    rev: v0.1.1
    hooks:
      - id: check-execution-order

  # - repo: https://github.com/codespell-project/codespell
  #   rev: v2.1.0
  #   hooks:
  #     - id: codespell
  #       types: [file]
  #       types_or: [python, pyi, markdown, rst, jupyter]
  #       args: [-L doas]
