[tool.black]
line-length = 99
target-version = ['py38']
exclude = '''
/(
    \.eggs
    | \.git
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
)/
'''

[tool.nbqa.addopts]
flake8 = [
    "--extend-ignore=E231, E203, E402",
    "--max-line-length=99"
]
