name: Programme-Quantenoptik
channels:
  - conda-forge
dependencies:
  # Jupyter
  - jupyterlab=3.1.4
  - jupyter-offlinenotebook=0.2
  - jupyterlab-autosave-on-focus-change=0.1.2
  # Python Kernel
  - ipykernel=6.0.3
  - python=3.8
  - ipywidgets
  - lmfit=1.0.2
  - numpy=1.21.1
  - pandas=1.3.1
  - scipy=1.6.2
  - scikit-learn=0.24.2
  - matplotlib=3.4.2
  - jupyterlab_widgets=1.0.0
  # testing
  - pytest=6.2.4
  - nbval=0.9.6
  - pre-commit=2.13.0
